#!/bin/bash

python3 SearchGraph.py romania Arad Bucharest
python3 SearchGraph.py romania Arad China
python3 SearchGraph.py romania Bucharest Arad
python3 SearchGraph.py romania India Arad
python3 SearchGraph.py romania Arad Arad
